Repository servicemesher/website, pull requests merged in 2019-07, with the labels that each got.

#53 Original: prow-quick-start-guide
  content/blog/prow-quick-start-guide/img-github-collaborators.png
  content/blog/prow-quick-start-guide/img-github-oauth-secret.png
  content/blog/prow-quick-start-guide/img-github-oauth.png
  content/blog/prow-quick-start-guide/img-github-pr.png
  content/blog/prow-quick-start-guide/img-github-pr2.png
  content/blog/prow-quick-start-guide/img-github-token.png
  content/blog/prow-quick-start-guide/img-github-webhook.png
  content/blog/prow-quick-start-guide/img-github-webhook2.png
  content/blog/prow-quick-start-guide/img-prow-job.png
  content/blog/prow-quick-start-guide/img-prow-plugins.png
  content/blog/prow-quick-start-guide/img-prow-status.png
  content/blog/prow-quick-start-guide/index.md
  content/blog/prow-quick-start-guide/traefik-ds.yaml
Labels: categories/cloud-native, kind/original, size/L, status/under-review, tag/kubernetes

#52 Original: Envoy feature explain - outlier detection.
  content/blog/envoy-feature-explain-outlier-detection/index.md
  content/blog/envoy-feature-explain-outlier-detection/luoguangming-aoseng.jpeg
Labels: categories/service-mesh, kind/original, size/M, status/under-review, tag/envoy

#55 深入了解Cilium多集群
  content/blog/deep-dive-into-cilium-multi-cluster/index.md
  static/img/blog/banners/bay-blue-boat-296242.jpg
Labels: kind/translation

#57 Original: 洞若观火：使用OpenTracing增强Istio的调用链跟踪-篇一
  content/blog/using-opentracing-with-istio-part-1/eshop-demo.jpg
  content/blog/using-opentracing-with-istio-part-1/index.md
  content/blog/using-opentracing-with-istio-part-1/istio-tracing-opentracing-in-depth.jpg
  content/blog/using-opentracing-with-istio-part-1/istio-tracing-opentracing.jpg
  content/blog/using-opentracing-with-istio-part-1/istio-tracing.jpg
  content/blog/using-opentracing-with-istio-part-1/monolith-microserivce.jpg
  content/blog/using-opentracing-with-istio-part-1/tracing_mental_model.png
  static/img/blog/banners/using-opentracing-with-istio-part-1.jpg
Labels: categories/tracing, kind/original

#61 add translation for #60
  content/blog/layer-7-observability-with-consul-service-mesh/1558253406-dashboard.png
  content/blog/layer-7-observability-with-consul-service-mesh/1558253409-l7metrics.png
  content/blog/layer-7-observability-with-consul-service-mesh/1558253412-requestcount.png
  content/blog/layer-7-observability-with-consul-service-mesh/1558253414-requestgrpc.png
  content/blog/layer-7-observability-with-consul-service-mesh/1558253416-requesttime.png
  content/blog/layer-7-observability-with-consul-service-mesh/1558253731-consul.png
  content/blog/layer-7-observability-with-consul-service-mesh/index.md
  mdl_style.rb
  static/img/blog/banners/franck-v-mMF7N2mNGCg-unsplash.jpg
Labels: categories/observability, categories/service-mesh, kind/translation, size/M

#62 GitOps与ChatOps的落地实践
  content/blog/gitops-and-chatops/ad5fbf65gy1g4vpmjzylfj20qy09tq4b.jpg
  content/blog/gitops-and-chatops/ad5fbf65gy1g4vr2yialfj20rp0bbmyd.jpg
  content/blog/gitops-and-chatops/ad5fbf65gy1g4vvoqggfoj22lk16aagu.jpg
  content/blog/gitops-and-chatops/ad5fbf65gy1g4vvrigyvlj20ec0bh40u.jpg
  content/blog/gitops-and-chatops/ad5fbf65gy1g4vwfdgd2xj20iu0ajwgc.jpg
  content/blog/gitops-and-chatops/index.md
  static/img/blog/banners/blogging-coding-copywriting-34140.jpg
Labels: kind/original, status/under-review

#63 new post: using opentracing with istio part 2
  content/blog/using-opentracing-with-istio-part-2/eshop-demo.jpg
  content/blog/using-opentracing-with-istio-part-2/index.md
  content/blog/using-opentracing-with-istio-part-2/istio-tracing-opentracing-kafka-rest.jpg
  content/blog/using-opentracing-with-istio-part-2/istio-tracing-opentracing-kafka.jpg
  content/blog/using-opentracing-with-istio-part-2/trace-graph.jpg
  static/img/blog/banners/using-opentracing-with-istio-part-2.jpg
Labels: categories/tracing, kind/original, tag/istio

#64 添加博客评论功能
  config.toml
  themes/hugo-universal-theme/layouts/_default/single.html
  themes/hugo-universal-theme/layouts/partials/comments.html
Labels: WIP, kind/hugo-theme

#69 更新图床
  README.md
Labels: approved, lgtm

#70 chore: add activity link to home page menu
  config.toml
Labels: approved, lgtm

#72 chore: add service mesh meetup 6th
  data/carousel/97.yaml
Labels: approved, lgtm, size/S

#76 Turn off auto-assign bot
  .github/auto_assign.yml
Labels: approved, lgtm, size/XS

#75 Add myself(SataQiu) as a committee member
  data/testimonials/qiushida.yaml
  static/img/testimonials/qiushida.jpg
Labels: approved, lgtm, size/XS

#77 add malphi intro
  data/testimonials/maruofei.yaml
  static/img/testimonials/maruofei.jpg
Labels: approved, lgtm, size/XS

#78 Add SOFAStack Meetup #3
  data/carousel/96.yaml
  data/carousel/97.yaml
Labels: approved, lgtm, size/S

#79 remove github app config
  .github/auto-comment.yml
  .github/auto_assign.yml
  .github/config.yml
Labels: approved, lgtm, size/M

#80 istio-analysis-5
  content/blog/istio-analysis-5/index.md
  static/img/blog/banners/boats.png
Labels: lgtm, size/XL

#82 Add myself(wujunze) as a committee member
  .gitignore
  data/testimonials/wujunze.yaml
  static/img/testimonials/wujunze.jpg
Labels: approved, lgtm, size/XS

#84 fix img
  static/img/testimonials/wujunze.jpg
Labels: approved, lgtm, size/XS

#86 change malphi photo size
  static/img/testimonials/maruofei.jpg
Labels: lgtm, size/XS

#87 Update ICP address
  themes/hugo-universal-theme/layouts/partials/footer.html
Labels: approved, lgtm, size/XS
