Repository servicemesher/website, pull requests merged in 2019-11, with the labels that each got.

#171 add linkerd2 tap analysis
  content/blog/linkerd2-proxy-tap-analysis/control-plane.png
  content/blog/linkerd2-proxy-tap-analysis/index.md
  content/blog/linkerd2-proxy-tap-analysis/proxy-tap.png
Labels: approved, kind/original, lgtm, size/L, tag/linkerd

#175 原创文章：如何降低Istio服务网格中Envoy的内存开销？
  content/blog/201911-envoy-memory-optimize/index.md
  static/img/blog/banners/201911-envoy-memory-optimize.jpg
Labels: approved, categories/service-mesh, kind/original, lgtm, size/L, status/under-review, tag/istio

#173 翻译文章“Kubernetes 垂直伸缩走向何方”投稿
  content/blog/kubernetes-vertical-pod-autoscaler/images/vpa-architecture.png
  content/blog/kubernetes-vertical-pod-autoscaler/index.md
Labels: approved, kind/translation, lgtm, size/L, tag/kubernetes

#177 Add istio zh-trans 20191129 report
  content/istio-zh/20191129/days_elapse_until_pr_merged.jpg
  content/istio-zh/20191129/index.html
  content/istio-zh/20191129/pr_author_top_10.jpg
  content/istio-zh/20191129/pr_reviewers_top_10.jpg
  content/istio-zh/20191129/prs_merged_per_day.jpg
Labels: approved, size/L

#178 Add Istio Chinese translation monthly pages
  config.toml
  content/istio-trans-monthly/20191129/days_elapse_until_pr_merged.jpg
  content/istio-trans-monthly/20191129/index.html
  content/istio-trans-monthly/20191129/pr_author_top_10.jpg
  content/istio-trans-monthly/20191129/pr_reviewers_top_10.jpg
  content/istio-trans-monthly/20191129/prs_merged_per_day.jpg
  content/istio-trans.md
  data/carousel/95.yaml
Labels: approved, size/M
