Repository servicemesher/website, pull requests merged in 2019-10, with the labels that each got.

#152 Replace description with summary
  GUIDELINE.md
  content/blog/architecting-kubernetes-clusters-choosing-a-worker-node-size/index.md
  content/blog/aws-app-mesh-application-level-networking-for-cloud-applications/index.md
  content/blog/custom-application-metrics-with-django-prometheus-and-kubernetes/index.md
  content/blog/journey-from-containerization-to-orchestration-and-beyond/index.md
  content/blog/kong-open-sources-kuma-the-universal-service-mesh/index.md
  content/blog/kubernetes-operator-in-python/index.md
  content/blog/running-apache-kafka-over-istio-benchmark/index.md
  content/blog/service-mesh-istio-limits-and-benefits-part-1/index.md
  content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
Labels: approved, size/S

#147 Translation: Istio circuit breaker #145
  content/blog/istio-circuit-breaking/index.md
Labels: approved, categories/service-mesh, kind/translation, lgtm, size/L, status/wait-for-publish, tag/istio

#155 Update zhaohuabing profile photo
  static/img/testimonials/zhaohuabing.jpg
Labels: approved, lgtm, size/XS

#156 Add Chengdu Service Mesh Meetup
  data/carousel/96.yaml
  data/carousel/97.yaml
Labels: approved, lgtm, size/S

#154 Translation: Horizontal Pod Autoscaling based on custom Istio metric
  content/blog/20190910-horizontal-pod-autoscaling-based-on-custom-istio-metrics/hpa_cust_metrics_istio.png
  content/blog/20190910-horizontal-pod-autoscaling-based-on-custom-istio-metrics/index.md
Labels: approved, categories/service-mesh, kind/translation, lgtm, size/L, status/under-review, tag/istio

#158 Update contact and activity
  content/activity.md
  content/contact.md
Labels: approved

#157 original: aws app mesh vs istio
  content/blog/compare-appmesh-with-istio/appmesh.png
  content/blog/compare-appmesh-with-istio/appmeshob.png
  content/blog/compare-appmesh-with-istio/appmeshroute.png
  content/blog/compare-appmesh-with-istio/arch.png
  content/blog/compare-appmesh-with-istio/aws-summit-appmesh.png
  content/blog/compare-appmesh-with-istio/index.md
Labels: approved, categories/service-mesh, kind/new-blog, kind/original, lgtm, size/L

#160 Update website logo
  config.toml
  content/blog/20190910-horizontal-pod-autoscaling-based-on-custom-istio-metrics/index.md
  content/blog/compare-appmesh-with-istio/index.md
  content/contact.md
  static/img/apple-touch-icon.png
  static/img/favicon.ico
  static/img/logo-new.png
  static/img/logo-small-new.jpg
  static/img/logosmall-new.png
  static/img/servicemesher-avatar-banner.jpg
  static/img/servicemesher-logo-new.png
  static/img/servicemesher-wechat-public.jpg
  static/img/servicemesher-wechat-tiny.jpg
  themes/hugo-universal-theme/i18n/zh.yaml
Labels: approved, size/S

#161 Translation: challenges-of-adopting-service-mesh-in-enterprise-organizations
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/bc-gw.png
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/deathstar.png
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/index.md
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/multi-tier-gw.png
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/push-down-gw.png
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/single-gateway.png
  content/blog/challenges-of-adopting-service-mesh-in-enterprise-organizations/start-slow-slide.png
Labels: approved, categories/service-mesh, kind/translation, lgtm, size/M

#163 new post: pilot code deep dive
  content/blog/201910-pilot-code-deep-dive/index.md
  content/blog/201910-pilot-code-deep-dive/pilot-discovery-client-request.svg
  content/blog/201910-pilot-code-deep-dive/pilot-discovery-initialization.svg
  content/blog/201910-pilot-code-deep-dive/pilot-discovery-push-changes.svg
  content/blog/201910-pilot-code-deep-dive/pilot-discovery-receive-connection.svg
  content/blog/201910-pilot-code-deep-dive/pilot-discovery-sequence.svg
  content/blog/201910-pilot-code-deep-dive/pilot-discovery.svg
  content/blog/201910-pilot-code-deep-dive/pilot-input-output.svg
Labels: approved, lgtm, size/XL

#164 Add Service Mesh Meetup Chengdu report
  content/blog/service-mesh-meetup-chengdu-20191028/index.md
  data/carousel/96.yaml
Labels: approved, size/M

#165 Update two links
  content/blog/service-mesh-meetup-chengdu-20191028/index.md
Labels: approved, size/XS

#153 增加一篇原创文章关于linkerd2 proxy 服务的 destination 组件 原理解析
  content/blog/linkerd2-proxy-destination-analysis/control-plane.png
  content/blog/linkerd2-proxy-destination-analysis/index.md
  content/blog/linkerd2-proxy-destination-analysis/proxy-destination.png
  static/img/blog/banners/00704eQkgy1fqer344dfggj49494elds.jpg
Labels: approved, kind/original, lgtm, size/L, status/under-review, tag/linkerd

#166 增加 reviewer 信息
  content/blog/linkerd2-proxy-destination-analysis/index.md
Labels: approved, size/XS

#167 更新博客中的图片地址
  content/blog/the-way-to-service-mesh-in-ant-financial/index.md
Labels: approved, lgtm, size/M

#169 更新 header 的配置和图片存储位置
  content/blog/201910-what-can-service-mesh-learn-from-sdn/index.md
Labels: approved, size/S
