Repository servicemesher/website, pull requests merged in 2019-09, with the labels that each got.

#126 Modify the blog and homepage banners
  content/blog/kubernetes-1.16-crd-ga-preview/index.md
  data/carousel/96.yaml
  data/carousel/97.yaml
Labels: approved, size/XS

#127 增加贡献和投稿指南
  CONTRIBUTING.md
  GUIDELINE.md
  README.md
Labels: approved, lgtm, size/M

#123 博客投稿：Contour 学习笔记（一）：使用 Contour 接管 Kubernetes 的南北流量
  content/blog/use-envoy-as-a-kubernetes-ingress/index.md
Labels: approved, categories/cloud-native, kind/original, lgtm, size/XL, status/under-review

#129 更新贡献指南
  GUIDELINE.md
  config.toml
  content/authors.md
  content/contributing-specification.md
  content/translators.md
Labels: approved, lgtm, size/M

#128 修改首页导航及作者译者排行页面标题
  GUIDELINE.md
Labels: approved, lgtm, size/XS

#132 用EnvoyFilter扩展Istio
  content/blog/using-envoyfilter-extend-istio/ads.png
  content/blog/using-envoyfilter-extend-istio/envoyfilter.png
  content/blog/using-envoyfilter-extend-istio/index.md
  content/blog/using-envoyfilter-extend-istio/isolated-after.png
  content/blog/using-envoyfilter-extend-istio/isolated-before.png
  content/blog/using-envoyfilter-extend-istio/source.png
  content/blog/using-envoyfilter-extend-istio/workflow.jpg
  static/img/blog/banners/envoyfilter.jpg
Labels: approved, lgtm, size/L

#131 #130-增加一篇转载
  content/blog/201909-build-full-micro-service-platform-by-spring-boot-with-kubernetes/application.png
  content/blog/201909-build-full-micro-service-platform-by-spring-boot-with-kubernetes/cloud-native.png
  content/blog/201909-build-full-micro-service-platform-by-spring-boot-with-kubernetes/image.png
  content/blog/201909-build-full-micro-service-platform-by-spring-boot-with-kubernetes/index.md
  content/blog/201909-build-full-micro-service-platform-by-spring-boot-with-kubernetes/微服务平台.png
  static/img/blog/banners/banner.jpg
Labels: approved, kind/reprint, lgtm, size/M, tag/kubernetes

#137 更新 banner 尺寸
  content/blog/201909-build-full-micro-service-platform-by-spring-boot-with-kubernetes/index.md
  static/img/blog/banners/banner-fjlajg.jpg
  static/img/blog/banners/banner.jpg
Labels: approved

#135 Translation: AWS App Mesh – Application-Level Networking for Cloud Applications #133
  content/blog/aws-app-mesh-application-level-networking-for-cloud-applications/index.md
Labels: approved, categories/service-mesh, kind/translation, lgtm, size/L

#140 fix broken link
  content/blog/knative-serving/index.md
Labels: approved, size/XS

#141 Translation: Kong’s Kuma Service Mesh Climbs the Kubernetes Wall
  content/blog/kong-open-sources-kuma-the-universal-service-mesh/index.md
  content/blog/kong-open-sources-kuma-the-universal-service-mesh/kuma-architecture.jpeg
  static/img/blog/banners/kuma-banner.jpeg
Labels: approved, kind/translation, lgtm, size/M

#142 fix keyword
  content/blog/kong-open-sources-kuma-the-universal-service-mesh/index.md
Labels: approved, lgtm, size/XS

#143 更新 Istio 中文官网链接
  config.toml
Labels: approved, size/XS

#136 Trans: architecting Kubernetes clusters - choosing a worker node size
  content/blog/architecting-kubernetes-clusters-choosing-a-worker-node-size/architecting-kubernetes-clusters-choosing-a-worker-node-size.png
  content/blog/architecting-kubernetes-clusters-choosing-a-worker-node-size/cluster-design.svg
  content/blog/architecting-kubernetes-clusters-choosing-a-worker-node-size/cluster-overload.svg
  content/blog/architecting-kubernetes-clusters-choosing-a-worker-node-size/index.md
  content/blog/architecting-kubernetes-clusters-choosing-a-worker-node-size/node-overload.svg
  static/img/blog/banners/architecting-kubernetes-clusters-choosing-a-worker-node-size.png
Labels: approved, kind/translation, lgtm, size/XL, status/under-review, tag/kubernetes

#144 Translation: Custom Application Metrics with Django, Prometheus, and Kubernetes #138
  content/blog/custom-application-metrics-with-django-prometheus-and-kubernetes/index.md
Labels: approved, categories/observability, kind/translation, lgtm, size/L, tag/kubernetes

#146 kubernetes autoscaling all you need to know - issues #121
  content/blog/k8s-autoscaling-all-you-need-to-know/index.md
  content/blog/k8s-autoscaling-all-you-need-to-know/kubernetes-autoscaling.jpg
  static/img/blog/banners/kubernetes-autoscaling.jpg
Labels: approved, kind/translation, lgtm, size/L, status/under-review, tag/kubernetes

#150 Review a blog
  content/blog/k8s-autoscaling-all-you-need-to-know/index.md
Labels: approved, size/M
