Repository servicemesher/website, pull requests merged in 2019-12, with the labels that each got.

#179 Delete the illegal links
  content/blog/istio-mixer-cache-part1-concepts/index.md
  content/blog/istio-service-mesh-tutorial/index.md
Labels: approved, size/XS

#180 change background img
  themes/hugo-universal-theme/static/img/fixed-background-2.jpg
Labels: approved, lgtm, size/XS

#181 Add service mesh meetup #9
  data/carousel/94.yaml
Labels: approved, size/S

#182 update mrf intro
  data/testimonials/maruofei.yaml
Labels: approved, lgtm, size/XS

#183 Add service mesh meetup #9 retrospect
  content/blog/service-mesh-meetup-hangzhou-20191228/index.md
  data/carousel/94.yaml
Labels: approved, size/M

#184 Update weight
  data/carousel/94.yaml
Labels: approved, size/XS
