Repository servicemesher/website, pull requests merged in 2019-08, with the labels that each got.

#88 istio-analysis-5 fix typo
  content/blog/istio-analysis-5/index.md
Labels: approved, lgtm, size/XS

#89 Translation: Three Technical Benefits of Service Meshes and their Operational Limitations, Part 2 #89
  content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
  static/img/blog/banners/limitandbenefit.jpg
Labels: approved, categories/service-mesh, kind/translation, lgtm, size/M

#90 优化一些翻译
  content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
Labels: approved, lgtm, size/M

#92 change banner size to 1000*750
  static/img/blog/banners/using-opentracing-with-istio-part-2.jpg
Labels: approved, lgtm, size/XS

#96 adjust banner size
  static/img/blog/banners/limitandbenefit.jpg
Labels: approved, lgtm, size/XS

#93 istio-analysis-6
  content/blog/istio-analysis-6/index.md
Labels: approved, lgtm, size/L

#95 构建云原生微服务网关系列-篇一：Ambassador
  content/blog/cloud-native-api-gateway-part-1/index.md
  static/img/blog/banners/blur-daylight-depth-of-field.jpg
Labels: approved, lgtm, size/L

#98 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#99 Fix insecure mixed content
  content/blog/istio-analysis-5/index.md
Labels: approved, size/S

#100 Translation: Running Apache Kafka over Istio - benchmark #81
  content/blog/running-apache-kafka-over-istio-benchmark/index.md
Labels: approved, kind/translation, size/L, tag/istio

#103 第六届service mesh meetup 回顾
  content/activity.md
  content/blog/service-mesh-meetup-guangzhou-20190811/index.md
Labels: lgtm, size/M

#105 added: design-patterns-for-microservices
  content/blog/design-patterns-for-microservices/blue-green.png
  content/blog/design-patterns-for-microservices/cb.png
  content/blog/design-patterns-for-microservices/event-sourcing.png
  content/blog/design-patterns-for-microservices/index.md
  content/blog/design-patterns-for-microservices/registry.png
  content/blog/design-patterns-for-microservices/saga1.png
  content/blog/design-patterns-for-microservices/saga2.png
  content/blog/design-patterns-for-microservices/treeview.png
Labels: approved, lgtm, size/L

#106 Add banner for #102
  static/img/blog/banners/dna-microservices-ar.jpg
Labels: lgtm, size/XS

#107 Fix typos
  content/blog/design-patterns-for-microservices/index.md
Labels: approved

#109 Change baidu verification file
  static/baidu_verify_e2ZdBvskHV.html
  static/baidu_verify_wjdXsxAhFS.html
Labels: approved, size/XS

#110 Added translation: kubernetes-operator-in-python
  content/blog/kubernetes-operator-in-python/index.md
  static/img/blog/banners/python-banner.png
Labels: approved, kind/translation, lgtm, size/L, tag/kubernetes

#111 Fluxcd-Merge
  content/blog/flux-get-start-easy/imgs/Change-to-1.14.2.png
  content/blog/flux-get-start-easy/imgs/First-Sync-Success.png
  content/blog/flux-get-start-easy/imgs/Flux-Deployed.png
  content/blog/flux-get-start-easy/imgs/Flux-Logo.png
  content/blog/flux-get-start-easy/imgs/GIthub-Commit-Success.png
  content/blog/flux-get-start-easy/imgs/Git-Repo-Config.png
  content/blog/flux-get-start-easy/imgs/New-Version-Success.png
  content/blog/flux-get-start-easy/imgs/Nginx-Deployment-Succeed.png
  content/blog/flux-get-start-easy/imgs/Nginx-Old-Curl.png
  content/blog/flux-get-start-easy/imgs/flux-cd-diagram.png
  content/blog/flux-get-start-easy/index.md
Labels: approved, kind/original, lgtm, size/L

#112 fix code fench style
  content/blog/prometheus-monitor-k8s-2/index.md
  content/blog/sidecar-design-pattern-in-microservices-ecosystem/index.md
Labels: approved, size/S

#115 投稿 Using knative as api aggregator layer
  content/blog/using-knative-as-api-aggregator-layer/img/bff.webp
  content/blog/using-knative-as-api-aggregator-layer/img/knative-logo-cmyk.png
  content/blog/using-knative-as-api-aggregator-layer/img/netline.png
  content/blog/using-knative-as-api-aggregator-layer/img/tuopu.png
  content/blog/using-knative-as-api-aggregator-layer/index.md
  static/img/blog/banners/using-knative-as-api-aggregator-layer.jpg
Labels: approved, categories/serverless, kind/original, lgtm, size/L, tag/knative

#116 change blog cover image
  static/img/blog/banners/using-knative-as-api-aggregator-layer.jpg
Labels: approved, lgtm, size/XS

#122 博客投稿：Kubernetes 1.16 CRD GA前瞻
  content/blog/kubernetes-1.16-crd-ga-preview/kubernetes-1.16-crd-ga-preview.md
  static/img/blog/banners/crd-ga.jpg
Labels: approved, lgtm, size/M

#120 Translation: journey-from-containerization-to-orchestration-and-beyond #113
  content/blog/journey-from-containerization-to-orchestration-and-beyond/index.md
Labels: approved, categories/cloud-native, kind/translation, lgtm, size/L
