Repository servicemesher/website, pull requests merged in 2020-01, with the labels that each got.

#185 Add Istio official website Chinese translation monthly
  content/istio-trans-monthly/20200102/index.html
  content/istio-trans-monthly/20200102/pr_author_top_10.jpg
  content/istio-trans-monthly/20200102/pr_reviewers_top_10.jpg
  content/istio-trans-monthly/20200102/prs_merged_per_day.jpg
  content/istio-trans.md
Labels: approved, size/L

#186 Update istio official website translation monthly report images
  content/istio-trans-monthly/20200102/index.html
  content/istio-trans-monthly/20200102/pr_author_top_10.jpg
  content/istio-trans-monthly/20200102/pr_author_top_10.png
  content/istio-trans-monthly/20200102/pr_merged_elapse_days.png
  content/istio-trans-monthly/20200102/pr_reviewers_top_10.jpg
  content/istio-trans-monthly/20200102/pr_reviewers_top_10.png
  content/istio-trans-monthly/20200102/prs_merged_per_day.jpg
  content/istio-trans-monthly/20200102/prs_merged_per_day.png
Labels: approved, size/XS

#187 Add Netease yantion service mesh practices
  content/blog/netease-yeation-service-mesh/imgs/ability1.png
  content/blog/netease-yeation-service-mesh/imgs/ability2.png
  content/blog/netease-yeation-service-mesh/imgs/apigateway.png
  content/blog/netease-yeation-service-mesh/imgs/migrate.png
  content/blog/netease-yeation-service-mesh/imgs/performance1.png
  content/blog/netease-yeation-service-mesh/imgs/roadmap.png
  content/blog/netease-yeation-service-mesh/imgs/servicemesh1.png
  content/blog/netease-yeation-service-mesh/imgs/servicemesh2.png
  content/blog/netease-yeation-service-mesh/imgs/servicemesh3.png
  content/blog/netease-yeation-service-mesh/index.md
  static/img/blog/banners/netease-yantion.jpg
Labels: approved, size/L

#188 Update blog
  content/blog/netease-yeation-service-mesh/imgs/wangguoyun.jpg
  content/blog/netease-yeation-service-mesh/index.md
Labels: approved, size/XS

#189 Update blog
  content/blog/netease-yeation-service-mesh/index.md
Labels: approved, size/M

#192 original: istio's self-salvation
  content/blog/istio-self-salvation/index.md
Labels: approved, categories/service-mesh, kind/new-blog, lgtm, size/L, status/under-review
