Repository servicemesher/website, pull requests merged in 2020-02, with the labels that each got.

#191 原创文章：2020年 Service Mesh 技术展望
  content/blog/2020-service-mesh-technology-outlook/index.md
Labels: WIP, approved, lgtm, size/M

#195 Hide the blog temporary
  content/blog/2020-service-mesh-technology-outlook/index.md
Labels: approved, size/L

#196 Add a blog about Service Mesh outlook 2020
  content/blog/2020-service-mesh-technology-outlook/index.md
  data/carousel/93.yaml
Labels: approved, size/M

#197 update gitalk
  themes/hugo-universal-theme/layouts/partials/comments.html
Labels: approved, lgtm, size/XS

#198 Translation: do-i-need-an-api-gateway-if-i-have-a-service-mesh #193
  content/blog/do-i-need-an-api-gateway-if-i-have-a-service-mesh/index.md
Labels: approved, categories/service-mesh, kind/translation, lgtm, size/L

#199 Service Mesh end user report
  content/blog/microservice-with-service-mesh-at-ant-financial/index.md
  content/blog/service-mesh-end-user-survey-report/chart1.png
  content/blog/service-mesh-end-user-survey-report/chart10.png
  content/blog/service-mesh-end-user-survey-report/chart11.png
  content/blog/service-mesh-end-user-survey-report/chart12.png
  content/blog/service-mesh-end-user-survey-report/chart13.png
  content/blog/service-mesh-end-user-survey-report/chart14.png
  content/blog/service-mesh-end-user-survey-report/chart15.png
  content/blog/service-mesh-end-user-survey-report/chart16.png
  content/blog/service-mesh-end-user-survey-report/chart2.png
  content/blog/service-mesh-end-user-survey-report/chart3.png
  content/blog/service-mesh-end-user-survey-report/chart4.png
  content/blog/service-mesh-end-user-survey-report/chart5.png
  content/blog/service-mesh-end-user-survey-report/chart6.png
  content/blog/service-mesh-end-user-survey-report/chart7.png
  content/blog/service-mesh-end-user-survey-report/chart8.png
  content/blog/service-mesh-end-user-survey-report/chart9.png
  content/blog/service-mesh-end-user-survey-report/index.md
  content/blog/sofa-mosn-0-4-0-changelog/index.md
  data/carousel/93.yaml
  static/img/blog/banners/survey.jpg
Labels: approved, size/M

#200 Network service mesh
  content/blog/202002-network-service-mesh/background.jpg
  content/blog/202002-network-service-mesh/cni.png
  content/blog/202002-network-service-mesh/index.md
  content/blog/202002-network-service-mesh/istio-on-top-of-nsm.png
  content/blog/202002-network-service-mesh/kubernetes-network-model.svg
  content/blog/202002-network-service-mesh/network-service-endpoint.jpg
  content/blog/202002-network-service-mesh/network-service-mesh.jpg
  content/blog/202002-network-service-mesh/network-service.jpg
  content/blog/202002-network-service-mesh/nsm-architecture.jpg
  content/blog/202002-network-service-mesh/qoe.png
  content/blog/202002-network-service-mesh/sdn.png
  content/blog/202002-network-service-mesh/sfc.png
  content/blog/202002-network-service-mesh/vpn-usecase-setup-connection.png
  content/blog/202002-network-service-mesh/vpn-usecase-yaml.png
  content/blog/202002-network-service-mesh/vpn-usecase.png
  static/img/blog/banners/202002-network-service-mesh.jpg
Labels: approved, kind/original, lgtm, size/L

#202 add blog istio-debug-with-envoy-log
  content/blog/istio-debug-with-envoy-log/index.md
Labels: approved, categories/service-mesh, kind/original, lgtm, size/L
