Repository servicemesher/website, pull requests merged in 2020-04, with the labels that each got.

#211 修改首页轮播图
  data/carousel/93.yaml
  data/carousel/94.yaml
  data/carousel/95.yaml
Labels: approved, size/M

#212 Update menu and footer
  config.toml
  themes/hugo-universal-theme/layouts/partials/footer.html
Labels: approved, size/S

#213 Add service mesh virtual meetup
  config.toml
  content/activity.md
  data/carousel/93.yaml
  data/testimonials/sunhaizhou.yaml
  data/testimonials/wujunze.yaml
  data/testimonials/yinlongfei.yaml
  data/testimonials/zhonghua.yaml
Labels: approved, size/L

#214 update readme
  README.md
  content/activity.md
  content/contributing-specification.md
Labels: approved, size/M

#215 提交原创文章：Istio 1.5 & Envoy 数据面 WASM 实践
  content/blog/202004-istio-envoy-wasm/index.md
  content/blog/202004-istio-envoy-wasm/wasm.png
Labels: size/L

#216 发布两篇博客
  content/blog/service-mesh-and-api-gateway/antfin-mesh-gateway.png
  content/blog/service-mesh-and-api-gateway/api-gateway-access-service-via-sidecar.png
  content/blog/service-mesh-and-api-gateway/api-gateway-access-service.png
  content/blog/service-mesh-and-api-gateway/api-gateway-based-on-sidecar-with-bff.png
  content/blog/service-mesh-and-api-gateway/api-gateway-based-on-sidecar.png
  content/blog/service-mesh-and-api-gateway/api-gateway-with-service-mesh.png
  content/blog/service-mesh-and-api-gateway/apigateway-and-servicemesh.pptx
  content/blog/service-mesh-and-api-gateway/bff-api-gateway.png
  content/blog/service-mesh-and-api-gateway/directions.png
  content/blog/service-mesh-and-api-gateway/index.md
  content/blog/service-mesh-and-api-gateway/one-sidecar-in-bff.png
  content/blog/service-mesh-and-api-gateway/relationship-with-bff.png
  content/blog/service-mesh-and-api-gateway/relationship-without-bff.png
  content/blog/service-mesh-and-api-gateway/two-sidecar-in-bff.png
  content/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog.png
  content/blog/sidecar-injection-iptables-and-traffic-routing/hook-connect.jpg
  content/blog/sidecar-injection-iptables-and-traffic-routing/index.md
  content/blog/sidecar-injection-iptables-and-traffic-routing/iptables.jpg
  content/blog/sidecar-injection-iptables-and-traffic-routing/sidecar-pattern.jpg
Labels: categories/service-mesh, kind/original, size/XXL
