Repository servicemesher/website, pull requests merged in 2020-03, with the labels that each got.

#205 Istio 1.5 release note 解读
  content/blog/istio-1-5-explanation/index.md
Labels: approved, categories/service-mesh, kind/original, lgtm, size/L

#206 fix
  content/blog/istio-1-5-explanation/index.md
Labels: lgtm, size/XS

#207 translation:redefining-extensibility-in-proxies
  content/blog/redefining-extensibility-in-proxies/index.md
  static/img/blog/banners/redefining-extensibility-in-proxies.jpg
Labels: approved, kind/translation, lgtm, size/M, tag/istio

#208 Add a blog about k8s scheduling-framework
  content/blog/202003-k8s-scheduling-framework/index.md
  content/blog/202003-k8s-scheduling-framework/sche.png
Labels: approved, kind/original, lgtm, size/XL, tag/kubernetes

#209 Add an live event
  data/carousel/93.yaml
  data/carousel/96.yaml
Labels: approved, size/S

#210 add blog about gitops progressive delivery with asm
  content/blog/202003-gitops-progressive-delivery-with-asm/index.md
Labels: approved, kind/original, lgtm, size/L
