Repository servicemesher/website, pull requests merged in 2020-05, with the labels that each got.

#217 service mesh virtual meetup
  content/blog/service-mesh-virtual-meetup-1/index.md
  data/carousel/93.yaml
Labels: approved, size/M

#218 博客：陌陌的 Service Mesh 实践
  content/blog/momo-service-mesh-practice/index.md
Labels: approved, size/L

#219 add new blog: Mecha：将Mesh进行到底
  content/blog/mecha/images/Bilgin Ibryam.png
  content/blog/mecha/images/coupling-in-different-architectures.jpg
  content/blog/mecha/images/dapr-building-block.png
  content/blog/mecha/images/dapr-overview.png
  content/blog/mecha/images/four-needs-of-app.jpg
  content/blog/mecha/images/mecha-core.png
  content/blog/mecha/images/mecha-implementation.png
  content/blog/mecha/images/mecha.jpg
  content/blog/mecha/images/multi-runtime-microservices-architecture.jpg
  content/blog/mecha/images/multi-runtime-microservices.jpg
  content/blog/mecha/images/publish.jpg
  content/blog/mecha/images/service-invocation.png
  content/blog/mecha/images/subscribe.jpg
  content/blog/mecha/images/traditional-platform-and-cloudnative-platform.jpg
  content/blog/mecha/index.md
Labels: approved, size/L

#222 Add Service Mesh Webinar #1
  content/blog/service-mesh-webinar-1/index.md
  data/carousel/91.yaml
  data/carousel/93.yaml
Labels: approved, size/M

#221 fix slide images of blog: momo-service-mesh-practice
  content/blog/momo-service-mesh-practice/images/slide_04.jpg
  content/blog/momo-service-mesh-practice/images/slide_05.jpg
  content/blog/momo-service-mesh-practice/images/slide_06.jpg
  content/blog/momo-service-mesh-practice/images/slide_07.jpg
  content/blog/momo-service-mesh-practice/images/slide_08.jpg
  content/blog/momo-service-mesh-practice/images/slide_10.jpg
  content/blog/momo-service-mesh-practice/images/slide_11.jpg
  content/blog/momo-service-mesh-practice/images/slide_13.jpg
  content/blog/momo-service-mesh-practice/images/slide_14.jpg
  content/blog/momo-service-mesh-practice/images/slide_16.jpg
  content/blog/momo-service-mesh-practice/images/slide_17.jpg
  content/blog/momo-service-mesh-practice/images/slide_18.jpg
  content/blog/momo-service-mesh-practice/images/slide_19.jpg
  content/blog/momo-service-mesh-practice/images/slide_20.jpg
  content/blog/momo-service-mesh-practice/images/slide_21.jpg
  content/blog/momo-service-mesh-practice/images/slide_22.jpg
  content/blog/momo-service-mesh-practice/images/slide_23.jpg
  content/blog/momo-service-mesh-practice/index.md
Labels: approved, lgtm, size/M

#223 Service Mesh 高可用在企业级生产中的实践
  content/blog/baidu-service-mesh-ha-practice/index.md
Labels: approved, size/L

#224 Update: 更新熔断部分图片。
  content/blog/baidu-service-mesh-ha-practice/index.md
Labels: approved, lgtm, size/XS

#225 Istio 1.6 explain
  content/blog/istio-1.6-explain/index.md
Labels: approved, categories/service-mesh, kind/original, lgtm, size/L, tag/istio
